# Generated by Django 4.1.7 on 2023-07-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('level', models.CharField(max_length=222)),
                ('ele', models.CharField(max_length=222)),
                ('ime', models.CharField(max_length=222)),
                ('description', models.TextField()),
            ],
        ),
    ]
