# Generated by Django 4.1.7 on 2023-07-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trek',
            old_name='image',
            new_name='img',
        ),
    ]
